# Generated by Django 4.0 on 2021-12-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nekomon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cookie_id',
        ),
        migrations.AddField(
            model_name='user',
            name='registration_ip',
            field=models.CharField(default=0, max_length=20, verbose_name='Registration IP'),
            preserve_default=False,
        ),
    ]
