# Generated by Django 4.0 on 2021-12-23 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nekomon', '0002_remove_user_cookie_id_user_registration_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='user_followed',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='nekomon.user'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='user_follower',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='nekomon.user'),
        ),
    ]
