# Generated by Django 4.0.4 on 2022-05-30 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nekomon', '0009_alter_post_in_response_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_header_image',
        ),
    ]
